spring:
  redis:
    database: 0
#    host : 127.0.0.1
#    port : 6379
    password: ly123456
    pool:
      max-active: 20
      max-wait: -1
      max-idle: 10
      min-idle: 0
    timeout: 0
    sentinel: 
      master: mymaster
      nodes: 192.168.35.101:16383,192.168.35.102:26383,192.168.35.102:36383